# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
