# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_publicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='codificacion',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
