# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_auto_20170502_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='codificacion',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
