# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_auto_20170504_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='nombreDoc',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
