# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('puesto', models.CharField(default='', max_length=200)),
                ('localidad', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('telefono', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Provincia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
