# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='empresa',
            new_name='organizacion',
        ),
    ]
