# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bornera', models.CharField(max_length=400)),
                ('pin', models.CharField(max_length=400)),
                ('orden', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=400)),
                ('nombre', models.CharField(max_length=400)),
                ('tipoSenal', models.CharField(max_length=400)),
                ('rango', models.CharField(max_length=400)),
                ('comentarios', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='conexion',
            name='senal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senales.Senal'),
        ),
        migrations.AddField(
            model_name='conexion',
            name='tipoConexion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senales.TipoConexion'),
        ),
    ]
