# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bornera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conexion',
            name='bornera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senales.Bornera'),
        ),
    ]
