# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senales', '0002_auto_20170424_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bornera',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
